---
title: "SePaaFil"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{SePaaFil}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Loading

For å kunne bruke funksjonenen i `orgdata` pakke, må pakken først gjort
tilgjengelig. Kjør denne komandoen:

```
library(orgdata)
```

Du får spørsmål om å oppdatere når ny versjon er tilgjengelig. Svar `YES` til
spørsmålet for å oppdatere. Evt. kan du også gjøre det manuelt ved å kjøre:

```
update_orgdata()
```

## Objekt 

OBS! HUSK Å ALLTID TILORDNE ET OBJEKT for `make_file()` og `read_file()`! Dvs.
bruk symbol `<-`. Ellers blir ikke resultatene tilgjengelig til lagring eller
videre behandling.

```
  dt <- make_file()
dvs. ^
```

## Les filer
Les original fil som det er ved å velge FILID

```
df <- les_fil(file = 12) #12 er en FILID 
```

`les_fil()` kan også brukes til å lese data ved å skrive hele stien til filen og
kan brukes til å lese filer i flere formater bl.a `.xls`, `.xlsx`, .`.dta`,
`.csv` etc. 

```
df <- les_fil("C:/Users/abc/FileName.csv")
```

## Lag filgrupper

Aggregere utvalgte fil eller filer med KOBLID

```
dt <- lag_fil("BEFOLKNING", koblid = 13)
dt <- lag_fil("BEFOLKNING", koblid = c(13, 15, 20))
```

Les filene i en filgruppe og bruk oppsettet som er spesifisert i Access

```
dt <- lag_fil("BEFOLKNING")

## les fra original filen selv om filene allerede er sjekket som KONTROLLERT
## dvs. allerede ligger i datavarehus
dt <- lag_fil("BEFOLKNING", raw = TRUE) 
```

## Lagre resultatene eller objekter

Objekt eller resultat fra `lag_fil()` ovenfor kan lages til en `.csv` fil ved å
kjøre:

```
save_file(dt, "BEFOLKNING")

```

Å lagre filen et annet utvalgte sted enn standard

```
save_file(dt, name = "MinFil", path = "C:/Navn/Til/Mappen")

```

Evt. hvis alle filer har ingen feil dvs. allerede kontrollert

```
lag_fil("BEFOLKNING", save = TRUE)
```

## Flere filgrupper

Hvis filene har blitt kontrollert så kan man lagre flere
FILGRUPPER med en gang, du velger selv måten du liker å gjøre det.
FILGRUPPE blir lagret som csv direkte. Ingen feilmelding er gitt.


```
fgp <- c("BEFOLKNING", "NEET", "DODE") #med " "
lag_filgrupper(fgp)
```

Eller

```
lag_filgrupper(BEFOLKNING, NEET, DODE) #uten
```


## Tips and Tricks

Lest bare et bestemt antall rader f.eks 5 rader
kan også brukes andre argumenter f.eks header = FALSE, skip = 0, sep = ; osv. Sjekk dokumentet.

```
les_fil(file = 1, nrows = 5)
```

Sjekk koding:

```
# Sjekk kategorier evt. omkoding
df <- les_fil(file = 1)
se_fil(df) #alle kolonner
se_fil(df, 1) #bare kolonne 1
se_fil(df, c(1:5)) #kolonner 1 til 5
se_fil(df, c(1,4,6))
se_fil(df, LANDBAK, INNVKAT)

df[, .N, keyby = landb] #kategori for landb i original data

dt <- lag_fil("TEST01", koblid = 1)
dt[, .N, keyby = LANDB] #kategori i omkodet aggregerte data
dt[, .N, keyby = LANDF]

# Få å finne kategorier bare for kommune eller spesifik kjonn
dt[LEVEL == "kommune", .N, keyby = LANDBAK]
dt[KJONN == 1, .N, keyby = LANDBAK]

# Sjekk koder f.eks GEO 1050110
dt[GEO == 1050110]

# Sjekk flere koder samtidig
dt[GEO %in% c(1050110, 1050122)]

# Sjekk GEO koder starter med 301
dt[GEO %like% "^301"]

# Sjekk GEO avsluttet med 99
dt[GEO %like% "99$"]

# Se alle rader i datasettet
View(df)

# Se logfiler
read_log("code00", 343) #343 er en KOBLID
read_log("code99", 343)

# Åpne hjemmeside
website()

# Sjekk versjon
packageVersion("orgdata")

# Se alle global options
names(orgdata:::opt.orgdata)
orgdata:::opt.orgdata #default verdi

```

## Debugging

For å se original koder og hva det skal bli kodet til

```
debug_opt("geo")
```

For å se hva kodene skal bli aggregert til
```
debug_opt("aggregate")
```

HUSK å nullstille etter bruk av debug funksjon
```
reset_opt()
```

Vis alle funksjonene som kjøres eller leses

```
show_functions = TRUE
```
